// Code generated by templ@v0.2.364 DO NOT EDIT.

package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"

	"github.com/raphi011/handoff/internal/model"
)

func TestRunTable(tsr model.TestSuiteRun) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"mt-8 flow-root\"><div class=\"-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8\"><div class=\"inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8\"><table class=\"min-w-full divide-y divide-gray-300\"><thead><tr><th scope=\"col\" class=\"whitespace-nowrap py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0\">")
		if err != nil {
			return err
		}
		var_2 := `Name`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th><th scope=\"col\" class=\"whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900\">")
		if err != nil {
			return err
		}
		var_3 := `Duration`
		_, err = templBuffer.WriteString(var_3)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</th></tr></thead><tbody class=\"divide-y divide-gray-200 bg-white\">")
		if err != nil {
			return err
		}
		for _, tr := range tsr.TestResults {
			_, err = templBuffer.WriteString("<tr><td class=\"whitespace-nowrap py-2 pl-4 pr-3 text-sm text-gray-500 sm:pl-0 flex items-center justify-start\">")
			if err != nil {
				return err
			}
			if tr.Result == "passed" {
				_, err = templBuffer.WriteString("<div class=\"flex-none rounded-full bg-green-400/10 p-1 text-green-400\"><div class=\"size-1.5 rounded-full bg-current\"></div></div>")
				if err != nil {
					return err
				}
			} else {
				_, err = templBuffer.WriteString("<div class=\"flex-none rounded-full bg-rose-400/10 p-1 text-rose-400\"><div class=\"size-1.5 rounded-full bg-current\"></div></div>")
				if err != nil {
					return err
				}
			}
			_, err = templBuffer.WriteString("<a href=\"")
			if err != nil {
				return err
			}
			var var_4 templ.SafeURL = templ.URL(fmt.Sprintf("/suites/%s/runs/%d/test/%s", tr.SuiteName, tsr.ID, tr.Name))
			_, err = templBuffer.WriteString(templ.EscapeString(string(var_4)))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\">")
			if err != nil {
				return err
			}
			var var_5 string = tr.Name
			_, err = templBuffer.WriteString(templ.EscapeString(var_5))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</a></td><td class=\"whitespace-nowrap px-2 py-2 text-sm text-gray-900\">")
			if err != nil {
				return err
			}
			var var_6 string = fmt.Sprintf("%dms", tr.DurationInMS)
			_, err = templBuffer.WriteString(templ.EscapeString(var_6))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</td><td>")
			if err != nil {
				return err
			}
			var var_7 string = fmt.Sprintf("%v", tr.Spans)
			_, err = templBuffer.WriteString(templ.EscapeString(var_7))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</td></tr>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</tbody></table></div></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
